name: qr-server
base: core24
version: '0.2.2'
summary: A server to generate QR codes
description: |
  Listen on a port and serve QR codes encoding the data after the hostname.
  For example, if running on localhost, then http://localhost/hello-there
  will create a QR code encoding the string hello-there.

  By default, listens on port 5000. To listen on another port, use
  `sudo snap set qr-server port=<port>`, with `<port>` being any available
  port number.

title: QR Server
icon: icon.png
license: MIT
source-code: https://github.com/olivercalder/qr
website: https://github.com/olivercalder/qr

grade: stable
confinement: strict

parts:
  qr-server:
    plugin: dump
    source: bin/
    organize:
      qr-server: bin/qr-server
      qr_server.py: bin/qr_server.py
    stage-packages:
      - qrencode

  python-dependencies:
    plugin: python
    source: .
    python-packages:
      - flask

apps:
  qr-server:
    command: bin/qr-server
    daemon: simple
    plugs:
      - network-bind
